apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-1
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: medium.awscdk.cloud
      http:
        paths:
          - backend:
              serviceName: apache-svc
              servicePort: 80
